changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security
      labels: [security]
    - title: Fixes
      labels: [bug, fix]
    - title: Features and interface
      labels: [enhancement, ui, accessibility]
    - title: Translations and documentation
      labels: [translation, documentation]
    - title: Build and dependencies
      labels: [build, dependencies, github-actions]
    - title: Other changes
      labels: ['*']
